unbind r
bind r source-file ~/.tmux.conf

setw -g mode-keys vi

set -g history-limit 10000
set -g history-file ~/.tmux_history

set -g allow-rename on

set -g mouse on
set -g renumber-windows on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

unbind Up
unbind Down
unbind Left
unbind Right
bind Up resize-pane -U 5
bind Down resize-pane -D 5
bind Left resize-pane -L 5
bind Right resize-pane -R 5
bind -n M-H previous-window
bind -n M-L next-window

# Display Popups

bind C-y display-popup -d '#{pane_current_path}' -w 80% -h 80% -E 'lazygit'
bind C-j display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf-tmux -p 80%,80% --reverse | xargs tmux switch-client -t"

set-option -g default-command bash
#set -g default-terminal "alacrity"
set -g default-terminal "screen-256color"
set -g terminal-overrides ",*:RGB"
#set -g default-shell "screen.xterm-256color"
set -g status-left '$(starship)'
set -g status-right "#[fg=white]#I #[fg=yellow]#H #R"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'jaclu/extrakto'
set -g @plugin 'hendrikmi/tmux-cpu-mem-monitor'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'

gray_light="#D8DEE9"
gray_medium="#ABB2BF"
gray_dark="#3B4252"
green_soft="#A3BE8C"
blue_muted="#81A1C1"
cyan_soft="#88C0D0"

set -g status-position top
set -g status-left-length 100
set -g status-style "fg=${gray_light},bg=default"
set -g status-left "#[fg=${green_soft},bold] #S #[fg=${gray_light},nobold] | "
set -g status-right " #{cpu}  #{mem} "
set -g window-status-current-format "#[fg=${cyan_soft}, bold]  #[underscore]#I:#W"
set -g window-status-format " #I:#W"
set -g message-style "fg=${gray_light},bg=default"
set -g mode-style "fg=${gray_dark},bg=${blue_muted}"
set -g pane-border-style "fg=${gray_dark}"
set -g pane-active-border-style "fg=${gray_medium}"

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'


# Resurrect
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

set -g @resurrect-dir "$HOME/.tmux/resurrect"
# Fixed post-save hook without sponge dependency
set -g @resurrect-hook-post-save-all "sed -i.bak 's/--cmd[^ ]* [^ ]* [^ ]*//g' $HOME/.tmux/resurrect/last"
set -g @resurrect-processes '"~nvim->nvim" "~vim->vim"'
set -g @resurrect-save-shell-history 'on'
set -g @continuum-restore-shell-history 'on'
set -g @resurrect-strategy-shell-history 'history'
set -g @logging-path "$HOME/.tmux/logs"
set -g @screen-capture-path "$HOME/.tmux/logs"
set -g @save-complete-history-path "$HOME/.tmux/logs"
# set -g @continuum-save-on-exit 'on'

# bind-key C-s save-session
# bind-key C-r restore-session

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
